export default eventHandler(async (event) => {
  const {
    id,
    reorder,
    stock,
    weight,
    lastupdate,
    lastsync,
    storeid,
    cprice,
    upc,
    isbn,
    sprice,
    ean,
    color,
    material,
    manufacturer,
    brand,
    mpn,
    imglist,
    name,
    category,
    type,
    sku,
    unit,
    location,
    menu,
    primaryimg,
    desc,
    grp,
    dimen,
    created_at,
  } = await readBody(event);
  const db = hubDatabase();

  await db
    .prepare(`
      INSERT INTO Items (
        id,
        reorder,
        stock,
        weight,
        lastupdate,
        lastsync,
        storeid,
        cprice,
        upc,
        isbn,
        sprice,
        ean,
        color,
        material,
        manufacturer,
        brand,
        mpn,
        imglist,
        name,
        category,
        type,
        sku,
        unit,
        location,
        menu,
        primaryimg,
        desc,
        grp,
        dimen,
        created_at
      ) VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
      )
    `)
    .bind(
      id,
      reorder,
      stock,
      weight,
      lastupdate,
      lastsync,
      storeid,
      cprice,
      upc,
      isbn,
      sprice,
      ean,
      color,
      material,
      manufacturer,
      brand,
      mpn,
      imglist,
      name,
      category,
      type,
      sku,
      unit,
      location,
      menu,
      primaryimg,
      desc,
      grp,
      dimen,
      created_at
    )
    .run();

  return {};
});